/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GameControllerServer;

// Program to run all of the other code in the correct order.
// Act out these steps using other files: Start interface, initiate connection, open game screen, start playing.

public class App {
    int x = 0;

    public static void main(String[] args) {
        App myObj = new App();
        System.out.println(myObj.x);
    }
}